version: '3.7'

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "11"
        INSTALL_MAVEN: "true"
        INSTAL_GRADLE: "true"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
    volumes:
      - ./logs:/mnt/logs      
      - ./keys:/mnt/keys
      - ./data/uploads:/mnt/uploads
      - ./data/data:/mnt/data
      - ../:/workspace
      # Docker
      - ~/.docker:/root/.docker:z
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh:z
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig:z
      # Kubernetes
      - ~/.kube:/root/.kube:z
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    entrypoint: zsh -c "while sleep 1000; do :; done"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: postgres:12.3
    container_name: db
    ports:
      - "5433:5432"
    volumes:
      - ${PGDATA_DIR}/pgdata:/var/lib/postgresql/data
    restart: always